SELECT A.TITLE
    ,A.BOARD_ID
    ,B.REPLY_ID
    ,B.WRITER_ID
    ,B.CONTENTS
    ,to_char(B.CREATED_DATE,'YYYY-MM-DD') AS CREATE_DATE
from USED_GOODS_BOARD A
inner join USED_GOODS_REPLY B on A.BOARD_ID = b.BOARD_ID
where TO_CHAR(A.CREATED_DATE,'YYYYMM')='202210'
order by B.CREATED_DATE, A.TITLE